# config.py

WIDTH = 480
HEIGHT = 480
CAM_INDEX = 0
FLUSH_READS = True
CAP_PROP_BUFFERSIZE = 3

MODEL_COMPLEXITY = 0
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5

AUTO_CALIBRATE_SECONDS = 10
EMA_ALPHA = 0.2
HIP_MARGIN = 20
HAND_CROSS_DIST = 60
